<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>AlgoriInstaller</AssemblyName>
    <RootNamespace>Algori.Installer</RootNamespace>
    <Version>1.1.0</Version>
    <Authors>Wanfranklin Alves</Authors>
    <Description>Instalador do Algori - Linguagem de programação em português</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
